name: ascat-dev
channels: !!python/tuple
- !!python/unicode
  'defaults'
- !!python/unicode
  'conda-forge'
dependencies:
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::ecmwf_grib=1.14.7=3
- conda-forge::jasper=1.900.1=4
- conda-forge::jpeg=9b=0
- conda-forge::libpng=1.6.28=0
- conda-forge::ncurses=5.9=10
- conda-forge::openssl=1.0.2h=1
- conda-forge::pandas=0.18.1=np111py27_0
- conda-forge::pip=8.1.2=py27_0
- conda-forge::py=1.4.31=py27_0
- conda-forge::pyflakes=1.2.3=py27_0
- conda-forge::pygrib=2.0.1=py27_3
- conda-forge::pyproj=1.9.5.1=py27_0
- conda-forge::pytest=2.9.2=py27_0
- conda-forge::python=2.7.12=1
- conda-forge::python-dateutil=2.5.3=py27_0
- conda-forge::pytz=2016.4=py27_0
- conda-forge::setuptools=23.0.0=py27_0
- conda-forge::six=1.10.0=py27_0
- conda-forge::sqlite=3.13.0=0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::zlib=1.2.8=3
- cpaulik::pybufr-ecmwf=0.81=np111py27_0
- curl=7.45.0=0
- hdf5=1.8.15.1=2
- libnetcdf=4.3.3.1=3
- mkl=11.3.3=0
- netcdf4=1.2.2=np111py27_0
- numpy=1.11.1=py27_0
- readline=6.2=2
- tk=8.5.18=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - coverage==4.1
  - decorator==4.0.10
  - ipdb==0.10.1
  - ipython==5.0.0
  - ipython-genutils==0.1.0
  - pathlib2==2.1.0
  - pexpect==4.2.0
  - pickleshare==0.7.2
  - prompt-toolkit==1.0.3
  - ptyprocess==0.5.1
  - pygeobase==0.3.13
  - pygeogrids==0.2.2
  - pygments==2.1.3
  - pykdtree==1.1.1
  - pynetcf==0.1.10
  - pytest-cov==2.3.0
  - simplegeneric==0.8.1
  - traitlets==4.2.2
  - wcwidth==0.1.7

