name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- pygrib
- netCDF4
- pykdtree
- h5py
- xarray
- dask
- pip
- pip:
  - cadati
  - requests
  - pdbufr
  - tqdm
  - lxml
  - pygeogrids
  - pynetcf
  - pytest
  - pytest-cov
  - pytest-mpl
  - build
  - flake8
  - yapf
