name: ascat_env
channels:
  - conda-forge
dependencies:
- numpy
- pandas
- pygrib
- netCDF4
- pykdtree
- h5py
- pip
- pip: 
  - pybufr-ecmwf
  - requests
  - tqdm
  - lxml
  - pygeobase>=0.4.0
  - pygeogrids>=0.3.0
  - pynetcf>=0.2.2
